### PR TITLE
add custom bot-api-url

### PR DESCRIPTION
**Pull request by azhdari**
In some countries, governments block requests to the telegram url. This PR is necessary to bypass this issue.

### CODE REVIEW

**Comment by SeppPenner** [comment]
Nice contribution, I didn't even think about the fact (Germany is quite free in this case), but in other countries this is a serious issue. I will try to provide an update soon.

**Comment by azhdari** [comment]
@SeppPenner 
It was a quite pleasure.  
However, I don't know why my name doesn't show up in contributors list, it's not a big deal though.

**Comment by SeppPenner** [comment]
I have honestly no idea why this is not displayed properly in the contributors section... Maybe because of the merging of the pull request?

**Comment by SeppPenner** [comment]
I will try something, let's see how this works.

**Comment by SeppPenner** [comment]
@all-contributors please add @azhdari for new bot api feature

**Comment by SeppPenner** [comment]
@all-contributors please add @azhdari for code doc

**Comment by SeppPenner** [comment]
Ok, looks quite good, I would say :D

**Comment by azhdari** [comment]
Thanks a lot @SeppPenner

**Pull request merged**
