### PR TITLE
Add support for topics

### PR DESCRIPTION
**Pull request by forcewake**
Add support to post messages to [topics](https://telegram.org/blog/topics-in-groups-collectible-usernames) via adding `message_thread_id` to `PostMessage`

### CODE REVIEW

**Comment by SeppPenner** [comment]
Looks good from the first view, I need to check this in detail. Plus, I somehow totally missed that feature in Telegram...

**Comment by forcewake** [comment]
Hey @SeppPenner 
Do you have any updates?

Thank you!

**Comment by SeppPenner** [comment]
Sorry for the long wait time. Will be available within the next version soon.

**Comment by SeppPenner** [comment]
@all-contributors please add @forcewake for code test

**Pull request merged**
